baseURL = 'http://www.2advanced.dev'
languageCode = 'en-us'
title = 'Italo Cunha, DCC/UFMG'
theme = 'terminal'

[params]
autoCover = false
oneHeadingSize = false
showLastUpdated = false
showMenuItems = 99
themeColor = 'blue'
# contentTypeName = "homepage"
# mainSections = ["homepage"]
# favicon = "favicon.ico"

[module]
[[module.imports]]
  path = 'github.com/hugomods/icons/vendors/font-awesome'

[languages]
  [languages.en]
    title = "Italo Cunha - DCC/UFMG"
    # copyright = ""

    # [lanchages.en.params]
    #   subtitle = "DCC/UFMG"
    #   keywords = ""
    #   menuMore = "Show more"
    #   readMore = "Read more"
    #   readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Italo's Homepage"
      logoHomeLink = "/about"
